# -*- coding: utf-8 -*-
"""BigData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZa0WOJnVfna_gSpNftc5JIJQFv5vzoP
"""

import threading
import time

def tarefa(nome):
    print(f"{nome} iniciando")
    time.sleep(2)
    print(f"{nome} finalizando")

#Threads para duas tarefas: multiprocessamento
tarefa1=threading.Thread(target=tarefa,args=('Tarefa 1',))
tarefa2=threading.Thread(target=tarefa,args=('Tarefa 2',))

#Inicialização do thread:
tarefa1.start()
tarefa2.start()

#Finalização do thread:
tarefa1.join()
tarefa2.join()

print("Processamento finalizado.")

#upload de arquivo csv ou excel

import polars as pl
import time

arquivo1=pl.read_csv("/content/202501_NovoBolsaFamilia.csv", separator=";", encoding="latin-1")
arquivo2=pl.read_csv("/content/202502_NovoBolsaFamilia.csv", separator=";", encoding="latin-1")

inicio_tempo=time.time()
df_polars=pl.concat([arquivo1,arquivo2])
display(df_polars.head()) #imprimir os 5 primeiros

print("Tempo de execução com Pandas", time.time()-inicio_tempo, "segundos")

#upload de arquivo csv ou excel

import pandas as pd
import time

arquivo1=pd.read_csv("/content/202501_NovoBolsaFamilia.csv", sep=";", encoding="latin-1")
arquivo2=pd.read_csv("/content/202502_NovoBolsaFamilia.csv", sep=";", encoding="latin-1")

inicio_tempo=time.time()
df_pandas=pd.concat([arquivo1,arquivo2])
display(df_pandas.head()) #imprimir os 5 primeiros

print("Tempo de execução com Pandas", time.time()-inicio_tempo, "segundos")

import pandas as pd
import polars as pl
import time

arquivo1=pl.read_csv("/content/202501_NovoBolsaFamilia.csv", separator=";", encoding="latin-1")

inicio_tempo=time.time()
df_polars1=pl.concat([arquivo1])

parquet1=df_polars1.write_parquet("/content/202501_NovoBolsaFamilia.parquet")
print("Tempo de execução com Pandas", time.time()-inicio_tempo, "segundos")
print(parquet1)

import pandas as pd
import polars as pl
import time

arquivo2=pl.read_csv("/content/202502_NovoBolsaFamilia.csv", separator=";", encoding="latin-1")

inicio_tempo=time.time()
df_polars2=pl.concat([arquivo2])

parquet2=df_polars2.write_parquet("/content/202502_NovoBolsaFamilia.parquet")
print("Tempo de execução com Pandas", time.time()-inicio_tempo, "segundos")
print(parquet2)

import psutil

processo=psutil.Process()
print('Uso de CPU:', processo.cpu_percent(),'%')
print('Uso de Memória:',processo.memory_info().rss/(1024**2),'MB')