# -*- coding: utf-8 -*-
"""BigData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZa0WOJnVfna_gSpNftc5JIJQFv5vzoP
"""

import threading
import time

def tarefa(nome):
    print(f"{nome} iniciando")
    time.sleep(2)
    print(f"{nome} finalizando")

#Threads para duas tarefas: multiprocessamento
tarefa1=threading.Thread(target=tarefa,args=('Tarefa 1',))
tarefa2=threading.Thread(target=tarefa,args=('Tarefa 2',))

#Inicialização do thread:
tarefa1.start()
tarefa2.start()

#Finalização do thread:
tarefa1.join()
tarefa2.join()

print("Processamento finalizado.")

#upload de arquivo csv ou excel

import polars as pl
import time

arquivo1=pl.read_csv("/content/202501_NovoBolsaFamilia.csv", separator=";", encoding="latin-1")
arquivo2=pl.read_csv("/content/202502_NovoBolsaFamilia.csv", separator=";", encoding="latin-1")

inicio_tempo=time.time()
df_polars=pl.concat([arquivo1,arquivo2])
display(df_polars.head()) #imprimir os 5 primeiros

print("Tempo de execução com Pandas", time.time()-inicio_tempo, "segundos")

#upload de arquivo csv ou excel

import pandas as pd
import time

arquivo1=pd.read_csv("/content/202501_NovoBolsaFamilia.csv", sep=";", encoding="latin-1")
arquivo2=pd.read_csv("/content/202502_NovoBolsaFamilia.csv", sep=";", encoding="latin-1")

inicio_tempo=time.time()
df_pandas=pd.concat([arquivo1,arquivo2])
display(df_pandas.head()) #imprimir os 5 primeiros

print("Tempo de execução com Pandas", time.time()-inicio_tempo, "segundos")

import pandas as pd
import polars as pl
import time

arquivo1=pl.read_csv("/content/202501_NovoBolsaFamilia.csv", separator=";", encoding="latin-1")

inicio_tempo=time.time()
df_polars1=pl.concat([arquivo1])

parquet1=df_polars1.write_parquet("/content/202501_NovoBolsaFamilia.parquet")
print("Tempo de execução com Pandas", time.time()-inicio_tempo, "segundos")
print(parquet1)

import pandas as pd
import polars as pl
import time

arquivo2=pl.read_csv("/content/202502_NovoBolsaFamilia.csv", separator=";", encoding="latin-1")

inicio_tempo=time.time()
df_polars2=pl.concat([arquivo2])

parquet2=df_polars2.write_parquet("/content/202502_NovoBolsaFamilia.parquet")
print("Tempo de execução com Pandas", time.time()-inicio_tempo, "segundos")
print(parquet2)

import psutil

processo=psutil.Process()
print('Uso de CPU:', processo.cpu_percent(),'%')
print('Uso de Memória:',processo.memory_info().rss/(1024**2),'MB')

import pandas as pd
import polars as pl
import time
from IPython.display import display

df_0125=pl.read_parquet('/content/202501_NovoBolsaFamilia.parquet')
df_0225=pl.read_parquet('/content/202501_NovoBolsaFamilia.parquet')
df_010225=pl.concat([df_0125,df_0225])
display(df_010225.head(7000000))#Concatenar arquivos parquet

resultado=(df_010225.filter(pl.col("NOME MUNICÍPIO")=="RIO DE JANEIRO")) # filtro do df_010225
display(resultado)

display(df_010225.select("CÓDIGO MUNICÍPIO SIAFI"))

display(df_010225.filter(pl.col("MÊS COMPETÊNCIA")==202501))

display(df_010225.select(pl.col("UF")).describe())

display(df_010225.sort("NOME MUNICÍPIO"))

display(df_010225.group_by('UF').agg(pl.col('NOME MUNICÍPIO').value_counts()))

df_010225=df_010225.slice(1)
display(df_010225.head())

df_010225=df_010225.with_columns(pl.lit(0).alias('DK'))
display(df_010225.head())

df_010225=df_010225.drop(['DK'])
display(df_010225.head())

import pandas as pd
import polars as pl
import time
from IPython.display import display
import psutil

#Concatenar arquivos parquet
df_0125=pl.read_parquet('/content/202501_NovoBolsaFamilia.parquet')
df_0225=pl.read_parquet('/content/202501_NovoBolsaFamilia.parquet')
df_010225=pl.concat([df_0125,df_0225])
display(df_010225.head(7000000))

# LAZY:
df_010225 = pl.DataFrame(df_010225).lazy()
# EXPLAIN:
df_010225.filter(pl.col("NOME MUNICÍPIO")=="RIO DE JANEIRO").explain()
# COLLECT:
resultado=(df_010225.filter(pl.col("NOME MUNICÍPIO")=="RIO DE JANEIRO").collect())
display(resultado)

# Exemplo de Aplicação para Atividades futuras:

consulta = (
    df_010225.filter(pl.col("NOME MUNICÍPIO") == "RIO DE JANEIRO")
    .group_by("NOME FAVORECIDO")
    .agg(pl.col("VALOR PARCELA").count())
)
print(consulta.explain())
resultado = consulta.collect()

# Análise Estatística com LazyEvaluation:
df_010225_lazy = df_010225.lazy()

consulta = (
    df_010225_lazy # Use the lazy version of the DataFrame
    .filter(pl.col("NOME MUNICÍPIO") == "RIO DE JANEIRO")
    .group_by("NOME FAVORECIDO")
    .agg(pl.col("VALOR PARCELA").mean().alias("MÉDIA VALOR PARCELA"),
         pl.col("VALOR PARCELA").sum().alias("SOMA VALOR PARCELA"))
)
print(consulta.explain())
resultado_estatisticas = consulta.collect()
display(resultado_estatisticas)

# Análise Estatística com LazyEvaluation:
df_010225_lazy = df_010225.lazy()

consulta = (
    df_010225_lazy # Use the lazy version of the DataFrame
    .filter(pl.col("NOME MUNICÍPIO") == "RIO DE JANEIRO")
    .with_columns(pl.col("VALOR PARCELA").str.replace(",", ".").cast(pl.Float64))
    .group_by("NOME FAVORECIDO")
    .agg(pl.col("VALOR PARCELA").mean().alias("MÉDIA VALOR PARCELA"),
         pl.col("VALOR PARCELA").sum().alias("SOMA VALOR PARCELA"))
)
print(consulta.explain())
resultado_estatisticas = consulta.collect()
display(resultado_estatisticas)

!pip install pandas numpy matplotlib seaborn

!pip install scilit-learn

!pip install scipy pyarrow

#Criar um novo lazy com estas informações
import pandas as pd
import polars as pl
from IPython.display import display
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import pearsonr, spearmanr

#Concatenar arquivos parquet
df_0125=pl.read_parquet('/content/202501_NovoBolsaFamilia.parquet')
df_0225=pl.read_parquet('/content/202501_NovoBolsaFamilia.parquet')
df_010225=pl.concat([df_0125,df_0225])
display(df_010225.head(7000000))

# LAZY:
df_es = pl.DataFrame(df_010225).lazy()
# EXPLAIN:
df_es.filter(pl.col("UF")=="ES").explain()
# COLLECT:
resultadoes=(df_es.filter(pl.col("UF")=="ES").collect())
display(resultadoes.head(100))

consulta_es = (
    df_es # Use the lazy version of the DataFrame
    .filter(pl.col("UF") == "ES")
    .with_columns(
        # Use the Polars .round() method on the expression
        pl.col("VALOR PARCELA").str.replace(",", ".").cast(pl.Float64).round(2).alias('VALOR PARCELA_ROUNDED')
    )
    .group_by("NOME MUNICÍPIO")
    .agg(pl.col("VALOR PARCELA_ROUNDED").mean().alias("MÉDIA VALOR PARCELA").round(2),
         pl.col("VALOR PARCELA_ROUNDED").sum().alias("SOMA VALOR PARCELA").round(2),
         pl.col("VALOR PARCELA_ROUNDED").min().alias("MENOR VALOR PARCELA").round(2),
         pl.col("VALOR PARCELA_ROUNDED").max().alias("MAIOR VALOR PARCELA").round(2),
         pl.col("VALOR PARCELA_ROUNDED").count().alias("QTD VALOR PARCELA").round(2),
         pl.col("VALOR PARCELA_ROUNDED").median().alias("MEDIANA VALOR PARCELA").round(2),
         pl.col("VALOR PARCELA_ROUNDED").var().alias("VARIÂNCIA VALOR PARCELA").round(2),
         pl.col("VALOR PARCELA_ROUNDED").std().alias("DESVIO PADRÃO VALOR PARCELA").round(2)
         )
)
print(consulta_es.explain())
resultado_estatisticas_es = consulta_es.collect()
display(resultado_estatisticas_es.head(100))

# Extrair colunas para visualização
# Collect the LazyFrame to a DataFrame before accessing columns
df_es_collected = df_es.collect()

# Now you can use get_column on the collected DataFrame
valores = df_es_collected.get_column("VALOR PARCELA").to_list()
qtd_beneficiarios = df_es_collected.get_column("NOME MUNICÍPIO").to_list()

# Calculando a correlação de Pearson para DataFrame "dados"
coef_pearson, p_valor = pearsonr(valores, qtd_beneficiarios)

print(coef_pearson)

#Título do Gráfico
plt.title("Relação entre Valor da Parcela e Quantidade de Municípios (Espírito santo)")
# Plota linha
plt.plot(valores,qtd_beneficiarios)
# Plota pontos
plt.scatter(valores,qtd_beneficiarios)
plt.show()

# Criar gráfico
plt.figure(figsize=(10, 6))
plt.scatter(valores, qtd_beneficiarios, alpha=0.5)
plt.title("Relação entre Valor da Parcela e Quantidade de Municípios (Espírito santo)")
plt.xlabel("Valor da Parcela (R$)")
plt.ylabel("Quantidade de Municípios")
plt.grid(True)
plt.show()

#Graficos de Correlação de Pearson

sns.set(style="whitegrid")
plt.figure(figsize=(10, 6))

# Usar .to_numpy() para evitar conversão para Pandas
# Access columns using square brackets and then collect before converting to numpy
sns.scatterplot(
    # Use .select() to choose the column from the LazyFrame, then collect and convert to numpy
    x=df_es.select("VALOR PARCELA").collect().to_numpy().flatten(), # Flatten the array as select returns a 2D array
    y=df_es.select("NOME MUNICÍPIO").collect().to_numpy().flatten(), # Flatten the array
    alpha=0.6
)

plt.title("Relação Valor da Parcela vs Qtd. Municípios")
plt.xlabel("Valor da Parcela (R$)")
plt.ylabel("Quantidade de Municípios")
plt.show()